on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: node_modules/*
          retention-days: 1

      - name: Upload the frontend build artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/node_modules/*
          retention-days: 1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Serverless tests
        run: npm run test
      - name: Frontend tests
        run: npm run test
        working-directory: frontend

  deploy-dev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v2
      - name: Download the build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Download the frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build

      - name: Deploy Dev
        run: CI=false npm run deploy-dev

  deploy-staging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/master'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - uses: actions/checkout@v2
      - name: Download the build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Download the frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build

      - name: Deploy Staging
        run: CI=false npm run deploy-staging

  deploy-production:
    name: Deploy to Production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v2
      - name: Download the build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Download the frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build

      - name: Deploy Production
        run: CI=false npm run deploy-prod
