on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      # Install serverless-stack
      - uses: bahmutov/npm-install@v1

      # Install react frontend
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Serverless tests
        run: npm run test
      - name: Frontend tests
        run: npm run test
        working-directory: frontend
      - name: Deploy app
        run: CI=false npm run deploy-prod
